---
- name: include distribution specific vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: include distribution specific install
  include: "{{ ansible_distribution }}.yml"

- name: Secure installation
  include: secure_installation.yml
