- name: stop mariadb
  service:
    name: mariadb
    state: stopped

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
  
- name: start mariadb
  service:
    name: mariadb
    state: started